# run: conda env create --file dpn-gpu-environment.yml
name: dpn-gpu-env
channels:
- defaults
- conda-forge
dependencies:
- python=3.6
- pywin32
- pandas
- numpy
- dill
- scipy
- pillow
- cython
- matplotlib=3.0.1
- scikit-image
- h5py
- ipython
- jupyter
- jupyterlab
- tensorflow-gpu
- keras=2.1.3
- imgaug
- opencv
- seaborn
- ipywidgets
